export const ROLES = {
  ADMIN: "admin",
  HOST: "host",
  DEALER: "dealer",
  PLAYER: "player",
  AUTHOR: "author",
};

export const ACCESS_RULES = {
  [ROLES.ADMIN]: [
    ROLES.ADMIN,
    ROLES.HOST,
    ROLES.DEALER,
    ROLES.PLAYER,
    ROLES.AUTHOR,
  ],
  [ROLES.HOST]: [ROLES.HOST, ROLES.DEALER, ROLES.PLAYER],
  [ROLES.DEALER]: [ROLES.DEALER, ROLES.PLAYER],
  [ROLES.PLAYER]: [ROLES.PLAYER],
};
export const REFERRAL_RULES = {
  [ROLES.ADMIN]: [
    ROLES.ADMIN,
    ROLES.HOST,
    ROLES.DEALER,
    ROLES.PLAYER,
    ROLES.AUTHOR,
  ],
  [ROLES.DEALER]: [ROLES.HOST, ROLES.DEALER, ROLES.PLAYER],
  [ROLES.HOST]: [ROLES.HOST, ROLES.PLAYER],
  [ROLES.PLAYER]: [ROLES.PLAYER],
};
